name: On create PRs

on: pull_request

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Post to the webhook ecosystem channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C05N48KD7RQ'
          slack-message: "<!subteam^S038F2G7LA3|growth> :tada: *NEW Ecosystem repository Pull Request*\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
